"""Initial migration

Revision ID: c1129b111eb4
Revises: 
Create Date: 2025-02-11 09:36:18.984975

"""
from alembic import op
import sqlalchemy as sa
from app.models.types import UUIDString


# revision identifiers, used by Alembic.
revision = 'c1129b111eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UUIDString(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'VISITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('device_tokens',
    sa.Column('id', UUIDString(length=36), nullable=False),
    sa.Column('user_id', UUIDString(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('qr_codes',
    sa.Column('id', UUIDString(length=36), nullable=False),
    sa.Column('owner_id', UUIDString(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_calls',
    sa.Column('id', UUIDString(length=36), nullable=False),
    sa.Column('visitor_id', UUIDString(length=36), nullable=True),
    sa.Column('owner_id', UUIDString(length=36), nullable=False),
    sa.Column('qr_code_id', UUIDString(length=36), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'CONNECTED', 'COMPLETED', 'MISSED', 'REJECTED', name='call_status_enum', native_enum=False), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_calls')
    op.drop_table('qr_codes')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
